services:
  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.production
    image: care_plus:latest
    volumes:
      - .:/var/www/html
    command: >
      sh -c " chown -R www-data:www-data /var/www/html/storage /var/www/html/bootstrap/cache && chmod -R 775 /var/www/html/storage /var/www/html/bootstrap/cache && php-fpm "
    networks:
      - app-network

  # Add queue worker service
  queue-worker:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.production
    command: php artisan queue:work --tries=3 --timeout=90
    depends_on:
      - php-fpm
    volumes:
      - .:/var/www/html
    networks:
      - app-network

  # Add scheduler service
  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.production
    command: php artisan schedule:work
    depends_on:
      - php-fpm
    volumes:
      - .:/var/www/html
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "8081:80"
      - "8444:443"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
    networks:
      - app-network

  database:
    image: mariadb:latest
    env_file:
      - .env.production
    ports:
      - "3309:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data: {}
