services:
  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.production
    image: care_plus:latest
    volumes:
      - .:/var/www/html
      - sqlite_data:/var/www/html/database:rw
    command: >
      sh -c "chown -R www-data:www-data /var/www/html/storage /var/www/html/bootstrap/cache && chmod -R 775 /var/www/html/storage /var/www/html/bootstrap/cache && php-fpm"
    networks:
      - app-network
    environment:
      CACHE_DRIVER: sqlite
      CACHE_DATABASE: /var/www/html/database/database.sqlite

  queue-worker:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.production
    environment:
      QUEUE_WORKER: "true"
      CACHE_DRIVER: sqlite
      CACHE_DATABASE: /var/www/html/database/database.sqlite
    volumes:
      - .:/var/www/html
      - sqlite_data:/var/www/html/database:rw
    depends_on:
      - database
    networks:
      - app-network
    restart: unless-stopped

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.production
    environment:
      SCHEDULER: "true"
      CACHE_DRIVER: sqlite
      CACHE_DATABASE: /var/www/html/database/database.sqlite
    volumes:
      - .:/var/www/html
      - sqlite_data:/var/www/html/database:rw
    depends_on:
      - database
    networks:
      - app-network
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "8081:80"
      - "8444:443"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
    networks:
      - app-network

  database:
    image: mariadb:latest
    env_file:
      - .env.production
    ports:
      - "3309:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data: {}
  sqlite_data:
    driver: local
