name: care_plus Deployement

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  deploy_to_droplet:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy Application
        run: |
          ssh -t -i ~/.ssh/id_rsa ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} << 'EOF'
          cd /var/www/html/care_plus || git clone https://github.com/VincentNdegwa/care_plus.git /var/www/html/care_plus && cd /var/www/html/care_plus
          git pull origin main

          # Stop and remove existing containers
          docker compose down

          # Build and start containers
          docker compose up -d --build

          # Clean up old images
          docker image prune -f

          # Run migrations
          # docker compose exec care_plus-php-fpm-1 php artisan migrate --force

          # Clear cache
          docker compose exec care_plus-php-fpm-1 php artisan optimize:clear
          docker compose exec care_plus-php-fpm-1 php artisan config:clear
          docker compose exec care_plus-php-fpm-1 php artisan route:clear
          docker compose exec care_plus-php-fpm-1 php artisan view:clear
          docker compose exec care_plus-php-fpm-1 php artisan cache:clear
          
          # Restart queue and scheduler
          docker compose restart queue-worker scheduler

          # Clear docker cache
          # docker builder prune -a --force
          EOF
